export const PROFILES_SUCCESS = 'PROFILES_SUCCESS';
export const PROFILES_FAILURE = 'PROFILES_FAILURE';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE';